---
Name: checkoutconfig
---
## Extensions
SilverStripe\Control\Controller:
  extensions:
    - SilverCommerce\Checkout\Extensions\ControllerExtension
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SilverCommerce\Checkout\Extensions\SiteConfigExtension
SilverCommerce\OrdersAdmin\Model\Invoice:
  extensions:
    - SilverStripe\Omnipay\Extensions\Payable
SilverStripe\Omnipay\Model\Payment:
  extensions:
    - SilverCommerce\Checkout\Extensions\PaymentExtension
SilverStripe\Security\Group:
  extensions:
    - SilverCommerce\Checkout\Extensions\GroupExtension

# Setup default registration config for users module
---
  Only:
    moduleexists: 'i-lateral/silverstripe-users'
---
ilateral\SilverStripe\Users\Users:
  require_verification: false
  send_verification_email: false
  new_user_groups:
    - ecommerce-customers