---
Name: checkoutconfig
---
## Extensions
SilverStripe\Control\Controller:
  extensions:
    - SilverCommerce\Checkout\Extensions\ControllerExtension
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SilverCommerce\Checkout\Extensions\SiteConfigExtension
SilverCommerce\OrdersAdmin\Model\Invoice:
  extensions:
    - SilverStripe\Omnipay\Extensions\Payable
    - SilverCommerce\Checkout\Extensions\InvoiceExtension
SilverStripe\Omnipay\Model\Payment:
  extensions:
    - SilverCommerce\Checkout\Extensions\PaymentExtension
SilverStripe\Security\Group:
  extensions:
    - SilverCommerce\Checkout\Extensions\GroupExtension